name: poc-pipeline

on: 
  workflow_dispatch:
    inputs:
      ticket:
        type: string
        required: true
        description: ticket id
        default: ticket
      name:
        type: string
        required: true
        description: service name
        default: name
      version:
        type: string
        required: true
        description: service version
        default: version

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "hello, world"
          echo ${{ inputs.ticket }}
          echo ${{ inputs.name }}
          echo ${{ inputs.version }}